# Generated by Django 3.2.5 on 2021-07-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prioroty',
            new_name='priority',
        ),
    ]
