# Generated by Django 3.2.5 on 2021-07-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_prioroty_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-09-09'),
            preserve_default=False,
        ),
    ]
